# copy all the tables
#!/bin/bash
set -e
cp fp-lib-table Aisler_complex_2_layer/
cp sym-lib-table Aisler_complex_2_layer/
cp fp-lib-table Aisler_complex_4_layer/
cp sym-lib-table Aisler_complex_4_layer/
cp fp-lib-table Aisler_complex_6_layer/
cp sym-lib-table Aisler_complex_6_layer/
cp fp-lib-table Aisler_simple_2_layer/
cp sym-lib-table Aisler_simple_2_layer/
cp fp-lib-table alu_box_10x10cm_minimal/
cp sym-lib-table alu_box_10x10cm_minimal/
cp fp-lib-table Hammond_1550Z113/
cp sym-lib-table Hammond_1550Z113/
cp fp-lib-table Hammond_1551G_JLCPCB_4layer/
cp sym-lib-table Hammond_1551G_JLCPCB_4layer/
cp fp-lib-table Hammond_1551G_OSH2layer/
cp sym-lib-table Hammond_1551G_OSH2layer/
cp fp-lib-table Hammond_1551G_OSH2L_devboard/
cp sym-lib-table Hammond_1551G_OSH2L_devboard/
cp fp-lib-table Hammond_1551G_OSH4layer/
cp sym-lib-table Hammond_1551G_OSH4layer/
cp fp-lib-table Hammond_1551G_OSH4L_devboard/
cp sym-lib-table Hammond_1551G_OSH4L_devboard/
cp fp-lib-table Hammond_1551M_OSH2layer/
cp sym-lib-table Hammond_1551M_OSH2layer/
cp fp-lib-table Hammond_1551R_OSH2layer/
cp sym-lib-table Hammond_1551R_OSH2layer/
cp fp-lib-table Hammond_1593K_JLCPCB_2layer/
cp sym-lib-table Hammond_1593K_JLCPCB_2layer/
cp fp-lib-table Hammond_1593K_OSH2layer/
cp sym-lib-table Hammond_1593K_OSH2layer/
cp fp-lib-table jlcpcb_2_layer/
cp sym-lib-table jlcpcb_2_layer/
cp fp-lib-table jlcpcb_4_layer/
cp sym-lib-table jlcpcb_4_layer/
cp fp-lib-table ModEleSys_1x1_module/
cp sym-lib-table ModEleSys_1x1_module/
cp fp-lib-table ModEleSys_1x2_module/
cp sym-lib-table ModEleSys_1x2_module/
cp fp-lib-table ModEleSys_backplane/
cp sym-lib-table ModEleSys_backplane/
cp fp-lib-table ModEleSys_backplane_DIN41612/
cp sym-lib-table ModEleSys_backplane_DIN41612/
cp fp-lib-table nuclone_devboard_medium/
cp sym-lib-table nuclone_devboard_medium/
cp fp-lib-table nuclone_devboard_small_2_layer/
cp sym-lib-table nuclone_devboard_small_2_layer/
cp fp-lib-table nuclone_devboard_small_4_layer/
cp sym-lib-table nuclone_devboard_small_4_layer/
cp fp-lib-table nuclone_expansion_small_2_layer/
cp sym-lib-table nuclone_expansion_small_2_layer/
cp fp-lib-table nuclone_expansion_small_UART+proto/
cp sym-lib-table nuclone_expansion_small_UART+proto/
cp fp-lib-table OSH_Park_2_layer/
cp sym-lib-table OSH_Park_2_layer/
cp fp-lib-table OSH_Park_4_layer/
cp sym-lib-table OSH_Park_4_layer/
cp fp-lib-table squantorTemplate/
cp sym-lib-table squantorTemplate/
