# copy all the tables
#!/bin/bash
cp fp-lib-table Aisler_simple_2_layer
cp sym-lib-table Aisler_simple_2_layer
cp fp-lib-table alu_box_10x10cm_jlc2layer
cp sym-lib-table alu_box_10x10cm_jlc2layer
cp fp-lib-table Hammond_1550Z113
cp sym-lib-table Hammond_1550Z113
cp fp-lib-table Hammond_1551G_JLCPCB_4layer
cp sym-lib-table Hammond_1551G_JLCPCB_4layer
cp fp-lib-table Hammond_1551G_OSH2layer
cp sym-lib-table Hammond_1551G_OSH2layer
cp fp-lib-table Hammond_1551G_OSH2L_devboard
cp sym-lib-table Hammond_1551G_OSH2L_devboard
cp fp-lib-table Hammond_1551G_OSH4layer
cp sym-lib-table Hammond_1551G_OSH4layer
cp fp-lib-table Hammond_1551G_OSH4L_devboard
cp sym-lib-table Hammond_1551G_OSH4L_devboard
cp fp-lib-table Hammond_1551M_OSH2layer
cp sym-lib-table Hammond_1551M_OSH2layer
cp fp-lib-table Hammond_1551R_OSH2layer
cp sym-lib-table Hammond_1551R_OSH2layer
cp fp-lib-table Hammond_1593K_JLCPCB_2layer
cp sym-lib-table Hammond_1593K_JLCPCB_2layer
cp fp-lib-table Hammond_1593K_OSH2layer
cp sym-lib-table Hammond_1593K_OSH2layer
cp fp-lib-table jlcpcb_2_layer
cp sym-lib-table jlcpcb_2_layer
cp fp-lib-table jlcpcb_4_layer
cp sym-lib-table jlcpcb_4_layer
cp fp-lib-table medium_nuclone_devboard
cp sym-lib-table medium_nuclone_devboard
cp fp-lib-table OSH_Park_2_layer
cp sym-lib-table OSH_Park_2_layer
cp fp-lib-table OSH_Park_4_layer
cp sym-lib-table OSH_Park_4_layer
cp fp-lib-table small_nuclone_devboard
cp sym-lib-table small_nuclone_devboard
cp fp-lib-table small_nuclone_expansion
cp sym-lib-table small_nuclone_expansion
cp fp-lib-table small_nuclone_expansion_shrunk
cp sym-lib-table small_nuclone_expansion_shrunk
cp fp-lib-table small_nuclone_expansion_shrunk_LPC824M201JHI33
cp sym-lib-table small_nuclone_expansion_shrunk_LPC824M201JHI33
